development:
  cloud_name: dlbulfw7b
  api_key: '591915317539343'
  api_secret: taaouoDq_wdknersEMxd6EU-IbU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dlbulfw7b
  api_key: '591915317539343'
  api_secret: taaouoDq_wdknersEMxd6EU-IbU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dlbulfw7b
  api_key: '591915317539343'
  api_secret: taaouoDq_wdknersEMxd6EU-IbU
  enhance_image_tag: true
  static_image_support: false
